function buildPublicTopLinksEn(b,a,c,e,d,f){b=b.replace("%2F","/");$(".header-moi").load("/portal/js/topLinksPublicEn.html?v=08082023",function(){$("#loginFormId").attr("action",f);$(".arabic-link").attr("href",b);$("#logoimg").attr("src",d+"?v=20200506");$(".logovp a").attr("href",e);$(".last_lang a").attr("href",b);$("#dateEn").html(a);$(".first").mouseover(function(){$("#dateDetail").show();$("#hijriEn").html("Hijri<br><strong>"+c+"</strong>");$("#gregorianEn").html("Gregorian<br><strong>"+a+"</strong>")});$(".first").mouseout(function(){$("#dateDetail").hide()})})}
function buildPublicTopLinksAr(b,a,c,e,d,f){b=b.replace("%2F","/");$(".header-moi").load("/portal/js/topLinksPublicAr.html?v=08082023",function(){$.getScript("/portal/js/responsive-switch.js");$("#loginFormId").attr("action",f);$(".arabic-link").attr("href",b);$("#logoimg").attr("src",d+"?v=20200506");$(".logovp a").attr("href",e);$(".last_lang a").attr("href",b);$("#dateAr").html(c);$(".first").mouseover(function(){$("#dateDetail").show();$("#hijriEn").html("\u0647\u062c\u0631\u064a<br><strong>"+c+"</strong>");$("#gregorianEn").html("\u0645\u064a\u0644\u0627\u062f\u064a<br><strong>"+
a+"</strong>")});$(".first").mouseout(function(){$("#dateDetail").hide()})})}
function buildRegTopLinksEn(b,a,c,e,d,f,h,g,k,l){b=b.replace("%2F","/");d="/portal/js/topLinksRegisteredEn.html?v=20200506";if("ar_SA"==g||"ar"==g)d="/portal/js/topLinksRegisteredEn_prefLangAr.html?v=20200506";$(".header-moi").load(d,function(){$(".arabic-link").attr("href",b);$("#logoimg").attr("src",h);$(".logovp a").attr("href",f);$(".profilePic").attr("src","/UserImageRender/UserImageRender?sessId="+l);$(".last_lang a").attr("href",b);$("#dateEn").html(a);$("#loginUserName").text(e);$(".first").mouseover(function(){$("#dateDetail").show();
$("#hijriEn").html("Hijri<br><strong>"+c+"</strong>");$("#gregorianEn").html("Gregorian<br><strong>"+a+"</strong>")});$(".first").mouseout(function(){$("#dateDetail").hide()});"false"===k&&$("#dashboardLink").show()})}
function buildRegTopLinksAr(b,a,c,e,d,f,h,g,k){b=b.replace("%2F","/");$(".header-moi").load("/portal/js/topLinksRegisteredAr.html?v=20200506",function(){$(".arabic-link").attr("href",b);$("#logoimg").attr("src",h);$(".logovp a").attr("href",f);$(".profilePic").attr("src","/UserImageRender/UserImageRender?sessId="+k);$(".last_lang a").attr("href",b);$("#dateAr").html(c);$("#loginUserName").text(e);$(".first").mouseover(function(){$("#dateDetail").show();$("#hijriEn").html("\u0647\u062c\u0631\u064a<br><strong>"+
c+"</strong>");$("#gregorianEn").html("\u0645\u064a\u0644\u0627\u062f\u064a<br><strong>"+a+"</strong>")});$(".first").mouseout(function(){$("#dateDetail").hide()});"false"===g&&$("#dashboardLink").show()})}
function buildPublicMenuEn(b){var a="."+b;$(".mainnav").load("/portal/js/menuPublicEn.html?v=08082023",function(){
$('.electronicinquiries a').attr("onClick","commoninitPopup('login-box2')").attr("href","#");$('.eservices a').attr("onClick","commoninitPopup('login-box2')").attr("href","#");
$.ajaxSetup({cache:!0});$.getScript("/portal/js/menu-custom.js");$(a).addClass("active");$(".login-link").on("click", function(){$(this).parent().toggleClass("selected")})})}
function buildPublicMenuAr(b){var a=getArabicActiveMenu(b);$(".mainnav").load("/portal/js/menuPublicAr.html?v=08082023",function(){
$('.electronicinquiries a').attr("onClick","commoninitPopup('login-box2')").attr("href","#");$('.eservices a').attr("onClick","commoninitPopup('login-box2')").attr("href","#");
$.ajaxSetup({cache:!0});$.getScript("/portal/js/menu-custom.js");$("."+a).addClass("active");$(".login-link").on("click", function(){$(this).parent().toggleClass("selected")})})}
function buildRegMenuEn(b,a,c){var e="/portal/js/menuRegisteredEn.html?v=20210701";if("ar_SA"==c||"ar"==c)e="/portal/js/menuRegisteredEn_prefLangAr.html?v=20210701";var d="."+b;$(".mainnav").load(e,function(){
$('.electronicinquiries a').attr("onClick","commoninitPopup('login-box2')").attr("href","#");$('.eservices a').attr("onClick","commoninitPopup('login-box2')").attr("href","#");
$.ajaxSetup({cache:!0});$.getScript("/portal/js/menu-custom.js");$(d).addClass("active");for(var b=a.length,c=0;c<b;c++)$(a[c].replace(/\//g,"").replace(/'/g,"")).show();$(".login-link").on("click", function(){$(this).parent().toggleClass("selected")})})}
function buildRegMenuAr(b,a){var c=getArabicActiveMenu(b);$(".mainnav").load("/portal/js/menuRegisteredAr.html?v=20210701",function(){
$('.electronicinquiries a').attr("onClick","commoninitPopup('login-box2')").attr("href","#");$('.eservices a').attr("onClick","commoninitPopup('login-box2')").attr("href","#");	
$.ajaxSetup({cache:!0});$.getScript("/portal/js/menu-custom.js");$("."+c).addClass("active");for(var b=a.length,d=0;d<b;d++)$(a[d].replace(/\//g,"").replace(/'/g,"")).show();$(".login-link").on("click", function(){$(this).parent().toggleClass("selected")})})}
function buildPublicMobileMenuEn(){$("#menu").load("/portal/js/mobileMenuPublicEn.html",function(){})}
function buildPublicMobileMenuAr(){$("#menu").load("/portal/js/mobileMenuPublicAr.html")}
function buildRegMobileMenuEn(){$("#menu").load("/portal/js/mobileMenuRegisteredEn.html")}
function buildRegMobileMenuAr(){$("#menu").load("/portal/js/mobileMenuRegisteredAr.html")}
function buildPublicFooterEn(){$(".footer").load("/portal/js/footerPublicEn.html?v=08082023")}
function buildPublicFooterAr(){$(".footer").load("/portal/js/footerPublicAr.html?v=08082023")}
function buildRegFooterEn(b){var a="/portal/js/footerRegisteredEn.html?v=20200506";if("ar_SA"==b||"ar"==b)a="/portal/js/footerRegisteredEn_prefLangAr.html?v=20200506";$(".footer").load(a)}
function buildRegFooterAr(){$(".footer").load("/portal/js/footerRegisteredAr.html?v=20200506")}
function buildWorklightHeaderEn(b,a,c,e,d){a=a.replace("%2F","/");$(".mobHeaderX").load("/portal/Dynamic/htmlPages/wl_headerEn.html",function(){$(".serviceTitle").attr("value",b);$(".menu-language").attr("value",a);$(".profileName").attr("value",c);$(".profilePic").attr("value","/UserImageRender/UserImageRender?sessId="+e);$(".userLoggedInStatus").attr("value",d)})}
function buildWorklightHeaderAr(b,a,c,e,d){a=a.replace("%2F","/");$(".mobHeaderX").load("/portal/Dynamic/htmlPages/wl_headerEn.html",function(){$(".serviceTitle").attr("value",b);$(".menu-language").attr("value",a);$(".profileName").attr("value",c);$(".profilePic").attr("value","/UserImageRender/UserImageRender?sessId="+e);$(".userLoggedInStatus").attr("value",d)})}
function buildWorklightFooter(){}
function getArabicActiveMenu(b){var a;switch(b){case "\u0627\u0644\u0631\u0626\u064a\u0633\u064a\u0629":a="home";break;case "\u0639\u0646 \u0627\u0644\u0648\u0632\u0627\u0631\u0629":a="aboutmoi";break;case "\u0627\u0644\u0627\u0633\u062a\u0639\u0644\u0627\u0645\u0627\u062a \u0627\u0644\u0625\u0644\u0643\u062a\u0631\u0648\u0646\u064a\u0629":a="electronicinquiries";break;case "\u0627\u0644\u062e\u062f\u0645\u0627\u062a \u0627\u0644\u0625\u0644\u0643\u062a\u0631\u0648\u0646\u064a\u0629":a="eservices";
break;case "\u0627\u0644\u0645\u0648\u0627\u0637\u0646\u0648\u0646":a="nationals";break;case "\u0627\u0644\u0645\u0642\u064a\u0645\u0648\u0646":a="expats";break;case "\u0627\u0644\u0625\u0645\u0627\u0631\u0627\u062a":a="emirates";break;case "\u0627\u0644\u0642\u0637\u0627\u0639\u0627\u062a":a="sectors";break;case "\u0627\u0644\u0623\u0639\u0645\u0627\u0644":a="business";break;case "\u0627\u0644\u062a\u0648\u0638\u064a\u0641":a="employment";break;case "\u0645\u0643\u062a\u0628\u064a":a="myoffice"}return a}
;
